import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import "./css/styles.css";
import AppProviders from "@providers/AppProviders";
import { ThemeModeScript } from 'flowbite-react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
    {/* className='dark' */}
      <body className={`${inter.className} bg-white dark:bg-black`}>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
