export * from './AcceptedPaymentCards';
export * from './AcceptedPayments';
export * from './CopyRight';
export * from './FooterAboutUsNav';
export * from './FooterDepartmentsNav';
export * from './FooterHelpNav';
export * from './FooterServicesNav';
export * from './MainFooter';
export * from './PaymentCard';
